version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username root --password example --eval 'db.adminCommand({ ping: 1 })' --authenticationDatabase admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

